= Registering a RHEL system
include::_attributes.adoc[]

For Red Hat Enterprise Linux machines, the `subscription-manager` solution allows users of RHEL to register their software, as well as download Red Hat tested and certified software, updates, and upgrades for RHEL.
In this section, you'll learn how to register and enable your Red Hat subscription to install any package on your system.

TIP: During the install process we've already registered our RHEL system using the installation GUI, but you may still want to learn how to do so from the CLI.

[#registering]
== Register and Activate a Red Hat Subscription

In order to register your RHEL machine to the Customer Portal, use the `subscription-manager` command with your credentials like so. The `--auto-attach` parameter enables the subscription at the same time.

[.console-input]
[source,bash]
----
subscription-manager register --username <username> --password <password>
----

The RHEL system sould confirm your registration with an output similar like so.

[.console-output]
[source,bash]
----
The system has been registered with ID: <id>
The registered system name is: localhost.localdomain
----

[#registering]
== Unregister a Red Hat Subscription

If you need to unregister your RHEL machine to re-register with a different account or for any other reason, use the following command.
[.console-input]
[source,bash]
----
subscription-manager unregister
----