= Registering a RHEL system
include::_attributes.adoc[]

While there are plenty of commands avaliable in Linux, there are a certain few that are cruital to your Linux experience.
Most likely, you'll end up using these commands daily.

[#whoami]
== Using `whoami`

The `whoami` command prints the user name of the currently logged-in user. Running the below command would result in the output of the username associated with current effective user id.

[.console-input]
[source,bash]
----
whoami
----

[.console-output]
[source,bash]
----
cclyburn
----

In addition, the `who` command is used to provide more system information, including when the system has booted last time, a list of logged-in users, and the system’s current run level.

[.console-input]
[source,bash]
----
who
----

[.console-output]
[source,bash]
----
cedricclyburn console  Sep 22 08:14 
----

[#man]
== Using `man`

The `man` command prints documentation for any Linux command on the system. 
You can learn about usage, related packages, and more from `man` pages.

[.console-input]
[source,bash]
----
man whoami
----

[.console-output]
[source,bash]
----
WHOAMI(1)                  General Commands Manual                 WHOAMI(1)

NAME
     whoami – display effective user id

SYNOPSIS
     whoami

DESCRIPTION
     The whoami utility has been obsoleted by the id(1) utility, and is
     equivalent to “id -un”.  The command “id -p” is suggested for normal
     interactive use.

     The whoami utility displays your effective user ID as a name.

EXIT STATUS
     The whoami utility exits 0 on success, and >0 if an error occurs.

SEE ALSO
     id(1)
----

[#whatis]
== Using `whatis`

Each manual page has a short description available within it.
`whatis` searches the manual page names and displays the manual page descriptions of any name matched, without having to look over the entire `man` page.

[.console-input]
[source,bash]
----
whatis whoami
----

[.console-output]
[source,bash]
----
whoami(1)                - display effective user id
----

[#reboot]
== Using `reboot`

The most straightforward way to restart your Linux server is with the `reboot` command. If you don't already have administrative privledges, you'll need them for this.

[.console-input]
[source,bash]
----
sudo reboot
----